#!/bin/bash

#Install HomeBrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

#Brew app installing
dev="docker git visual-studio-code iterm2 bat"
general="alfred zerotier-one qbittorent spotify iina discord keepassx"
cloudStorage="google-drive-file-stream dropbox"
# wireshark, 
echo "Installing Brew Casks..."
echo "Installing Dev Stuff"
brew cask install $dev
echo "Installing General Stuff"
brew cask install $general
echo "Installing cloud Storage"
brew cask install $cloudStorage
echo "Installing Oh-My-Zsh..."
#Oh-My-Zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#Powerlevel 10k | Terminal Theme 
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

echo "Installing Brew Stuff"
brew install mas dust tealdeer gping
tldr --update
# MAS (Mac appstore interface) a tool which allows you to install apps from mac app store via CLI 
# think this is a key 1 2 3 ? 
#  Adblock, word, excel,
echo "Installing Mac App Store Apps"
mas install 408981434 1402042596 462054704 46205843 
