context.modules = [
	# This is a virtual default device to solve problems related to multi channel devices 
	{   name = libpipewire-module-loopback
		args = {
			node.description = "Rode Virtual: Main Output"
			capture.props = {
				node.name = "Rode_Main_Output"
				media.class = "Audio/Sink"
				audio.position = [ FL FR ]
				audio.channels = 2
			}
			playback.props = {
				node.name = "playback.Rode_Main_Output"
				audio.position = [ AUX0 AUX1 ]
				audio.channels = 2
                target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IR0062241-00.pro-output-1"
				stream.dont-remix = true
				node.passive = true
			}
		}
	},
    
    {   name = libpipewire-module-loopback
		args = {
			node.description = "Rode Virtual: Game"
			capture.props = {
				node.name = "Rode_Game_Out"
                node.description = "Rode Virtual: Game"
				media.class = "Audio/Sink"
                audio.channels = 2
				audio.position = [ FL FR ]
			}
			playback.props = {
                target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IR0062241-00.pro-output-1"
                audio.position = [ AUX2 AUX3 ]
				stream.dont-remix = true
				node.passive = true
				audio.channels = 2

			}
		}
	},

	{   name = libpipewire-module-loopback
		args = {
			node.description = "Rode Virtual: Music"
			capture.props = {
				node.name = "Rode_Music_Out"
                node.description = "Rode Virtual: Music"
				media.class = "Audio/Sink"
                audio.channels = 2
				audio.position = [ FL FR ]
			}
			playback.props = {
                target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IR0062241-00.pro-output-1"
                audio.position = [ AUX4 AUX5 ]
				stream.dont-remix = true
				node.passive = true
			}
		}
	},

	{   name = libpipewire-module-loopback
		args = {
			node.description = "Rode Virtual: A"
			capture.props = {
				node.name = "Rode_A_Out"
                node.description = "Rode Virtual: A"
				media.class = "Audio/Sink"
                audio.channels = 2
				audio.position = [ FL FR ]
			}
			playback.props = {
                target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IR0062241-00.pro-output-1"
                audio.position = [ AUX6 AUX7 ]
				stream.dont-remix = true
				audio.channels = 2
				node.passive = true
			}
		}
	},

	{   name = libpipewire-module-loopback
		args = {
			node.description = "Rode Virtual: B"
			capture.props = {
				node.name = "Rode_B_Out"
                node.description = "Rode Virtual: B"
				media.class = "Audio/Sink"
                audio.channels = 2
				audio.position = [ FL FR ]
			}
			playback.props = {
                target.object = "alsa_output.usb-R__DE_RODECaster_Duo_IR0062241-00.pro-output-1"
                audio.position = [ AUX8 AUX9 ]
				stream.dont-remix = true
				node.passive = true
			}
		}
	}
]

context.objects = [
	# Idk what the difference between modules and objects but they do be different
]