#!/usr/bin/env bash
# Toggles noctalia bar and game_mode.kdl (gaps, etc.) together as a "zen mode"
STATE=/tmp/niri-zen-mode
NIRI_KDL=~/.config/niri/niri.kdl

if [[ -f "$STATE" ]]; then
    # Exit zen: disable game_mode include, show bar
    sed -i 's|^include "./game_mode.kdl"|//include "./game_mode.kdl"|' "$NIRI_KDL"
    noctalia msg bar-show
    noctalia msg dock-show
    rm "$STATE"
else
    # Enter zen: enable game_mode include, hide bar
    sed -i 's|^//include "./game_mode.kdl"|include "./game_mode.kdl"|' "$NIRI_KDL"
    niri msg action load-config-file
    noctalia msg bar-hide
    noctalia msg dock-hide
    touch "$STATE"
fi
